name: local_colab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # Core analysis/plotting
  - numpy=1.26.4
  - pandas=1.5.2
  - matplotlib=3.7.0
  - seaborn=0.12.1

  # Stats
  - scipy=1.14.1
  - statsmodels=0.14.4
  - pingouin=0.5.5

  # I/O
  - openpyxl=3.1.5
  - h5py=3.12.1

  # ML / utils
  - scikit-learn=1.5.2
  - joblib=1.4.2
  - tqdm=4.67.1
  - optuna=4.2.1

  # Notebook execution stack
  - nbclient=0.8.0
  - nbformat=5.10.4
  - ipykernel=6.29.5
  - pyzmq=25.1.2
  - tornado  # leave unpinned to resolve compat on Windows

  # Optional metapackage if you want the CLI tools (not strictly required for your runner)
  - jupyter

  - pip
  - pip:
      # pip-only
      - mat73
     
